# Generated by Django 6.1 on 2026-09-26 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150, verbose_name='Usuario / Sistema')),
                ('categoria', models.CharField(choices=[('BOMBA', 'Bomba de Riego'), ('RECETA', 'Receta / Parámetros'), ('ALERTA', 'Alerta / Contingencia'), ('SISTEMA', 'Sistema Operativo'), ('SEGURIDAD', 'Seguridad y Acceso'), ('HUERTA', 'Gestión de Huerta')], max_length=30, verbose_name='Categoría')),
                ('descripcion', models.TextField(verbose_name='Descripción del Evento')),
                ('ip_origen', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP de Origen')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
            ],
            options={
                'verbose_name': 'Evento de Auditoría',
                'verbose_name_plural': 'Registro de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Huerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Huerta')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación Física')),
                ('esp32_device_id', models.CharField(help_text='Ej: ESP32-S3-AQUA-01', max_length=50, unique=True, verbose_name='ID Microcontrolador ESP32')),
                ('cultivo_activo', models.CharField(default='Rúcula', max_length=50, verbose_name='Cultivo Activo')),
                ('estado', models.CharField(choices=[('ONLINE', 'Online (En línea)'), ('OFFLINE', 'Offline (Desconectado)')], default='ONLINE', max_length=20, verbose_name='Estado de Conexión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('ultimo_reporte', models.DateTimeField(auto_now=True, verbose_name='Último Reporte')),
            ],
            options={
                'verbose_name': 'Huerta',
                'verbose_name_plural': 'Huertas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.CharField(max_length=50, unique=True, verbose_name='Cultivo / Variedad')),
                ('tr_dia', models.IntegerField(default=15, verbose_name='Tiempo Riego Día (seg)')),
                ('td_dia', models.IntegerField(default=240, verbose_name='Tiempo Descanso Día (seg)')),
                ('tr_noche', models.IntegerField(default=10, verbose_name='Tiempo Riego Noche (seg)')),
                ('td_noche', models.IntegerField(default=480, verbose_name='Tiempo Descanso Noche (seg)')),
                ('modo_manual', models.BooleanField(default=False, verbose_name='Modo Manual')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Receta de Riego',
                'verbose_name_plural': 'Recetas de Riego',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150, verbose_name='Autor')),
                ('rol', models.CharField(default='Encargado', max_length=50, verbose_name='Rol')),
                ('cultivo', models.CharField(max_length=50, verbose_name='Cultivo Observado')),
                ('observacion', models.TextField(verbose_name='Nota u Observación Técnica')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('huerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='api.huerta', verbose_name='Huerta')),
            ],
            options={
                'verbose_name': 'Entrada de Bitácora',
                'verbose_name_plural': 'Bitácora de Cultivo',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Telemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField(verbose_name='Temperatura (°C)')),
                ('humedad', models.FloatField(verbose_name='Humedad Relativa (%)')),
                ('nivel_agua', models.IntegerField(verbose_name='Nivel de Agua (%)')),
                ('estado_agua', models.CharField(choices=[('WATER_OK', 'WATER_OK - Nivel Adecuado (>10%)'), ('WATER_LOW', 'WATER_LOW - Nivel Bajo (<=10%)'), ('WATER_EMPTY', 'WATER_EMPTY - Tanque Vacío (<=5%)')], default='WATER_OK', max_length=20, verbose_name='Estado Hídrico')),
                ('bomba_activa', models.BooleanField(default=False, verbose_name='Estado Bomba')),
                ('vpd', models.FloatField(blank=True, null=True, verbose_name='VPD (kPa)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('huerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetrias', to='api.huerta', verbose_name='Huerta')),
            ],
            options={
                'verbose_name': 'Lectura de Telemetría',
                'verbose_name_plural': 'Historial de Telemetría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
